skinparam monochrome true
skinparam shadowing false
skinparam defaultFontSize 13
skinparam ArrowThickness 1.1
skinparam wrapWidth 200
skinparam noteBorderColor #000000
skinparam usecaseBackgroundColor #FFFFFF
skinparam usecaseBorderColor #000000
skinparam actorBorderColor #000000
skinparam rectangleBorderColor #000000
skinparam databaseBackgroundColor #FFFFFF
skinparam databaseBorderColor #000000
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #000000
skinparam sequenceParticipantBackgroundColor #FFFFFF
skinparam sequenceParticipantBorderColor #000000
skinparam activityBackgroundColor #FFFFFF
skinparam activityBorderColor #000000
skinparam componentBackgroundColor #FFFFFF
skinparam componentBorderColor #000000
skinparam nodeBackgroundColor #FFFFFF
skinparam nodeBorderColor #000000
